package com.checkers.service;

import com.checkers.engine.Board;
import com.checkers.engine.CheckersRulesEngine;
import com.checkers.engine.EngineMove;
import com.checkers.engine.GameOutcome;
import com.checkers.engine.MoveResult;
import com.checkers.engine.Piece;
import com.checkers.engine.PieceType;
import com.checkers.engine.Square;
import com.checkers.model.enums.BotDifficulty;
import com.checkers.model.enums.PieceColor;
import com.checkers.websocket.dto.MoveMessage;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * AI opponent using minimax + alpha-beta on top of {@link CheckersRulesEngine}.
 * <ul>
 *   <li>EASY — depth 2, random among top-5 scored moves</li>
 *   <li>MEDIUM — depth 4, random among top-3</li>
 *   <li>HARD — depth 6, best move (top-1)</li>
 * </ul>
 */
@Service
public class BotService {

    private static final int MAN_VALUE = 100;
    private static final int KING_VALUE = 280;
    private static final int MOBILITY_WEIGHT = 3;
    private static final int WIN_SCORE = 100_000;

    private final CheckersRulesEngine rulesEngine = new CheckersRulesEngine();

    public EngineMove chooseMove(Board board, BotDifficulty difficulty) {
        List<EngineMove> legal = rulesEngine.legalMoves(board);
        if (legal.isEmpty()) {
            return null;
        }

        BotDifficulty level = difficulty == null ? BotDifficulty.MEDIUM : difficulty;
        int depth = depthFor(level);
        int topN = topNFor(level);
        PieceColor botColor = board.turn();

        List<ScoredMove> scored = new ArrayList<>(legal.size());
        int alpha = Integer.MIN_VALUE / 2;
        int beta = Integer.MAX_VALUE / 2;

        for (EngineMove move : legal) {
            Board next = apply(board, move);
            int score = minimax(next, depth - 1, alpha, beta, false, botColor);
            scored.add(new ScoredMove(move, score));
            alpha = Math.max(alpha, score);
        }

        scored.sort(Comparator.comparingInt(ScoredMove::score).reversed());
        int limit = Math.min(topN, scored.size());
        return scored.get(ThreadLocalRandom.current().nextInt(limit)).move();
    }

    /** Stage-1 signature compatibility. */
    public MoveMessage chooseMove(Long gameId, BotDifficulty difficulty) {
        throw new UnsupportedOperationException("Use chooseMove(Board, BotDifficulty)");
    }

    public long thinkingDelayMs(BotDifficulty difficulty) {
        return switch (difficulty == null ? BotDifficulty.MEDIUM : difficulty) {
            case EASY -> 300L + ThreadLocalRandom.current().nextLong(400);
            case MEDIUM -> 600L + ThreadLocalRandom.current().nextLong(700);
            case HARD -> 900L + ThreadLocalRandom.current().nextLong(900);
        };
    }

    private int minimax(Board board, int depth, int alpha, int beta, boolean maximizing, PieceColor botColor) {
        rulesEngine.refreshOutcome(board);
        GameOutcome outcome = board.outcome();
        if (outcome != GameOutcome.IN_PROGRESS) {
            return terminalScore(outcome, botColor);
        }
        if (depth <= 0) {
            return evaluate(board, botColor);
        }

        List<EngineMove> moves = rulesEngine.legalMoves(board);
        if (moves.isEmpty()) {
            return evaluate(board, botColor);
        }

        if (maximizing) {
            int best = Integer.MIN_VALUE / 2;
            for (EngineMove move : moves) {
                int score = minimax(apply(board, move), depth - 1, alpha, beta, false, botColor);
                best = Math.max(best, score);
                alpha = Math.max(alpha, best);
                if (beta <= alpha) {
                    break;
                }
            }
            return best;
        }

        int best = Integer.MAX_VALUE / 2;
        for (EngineMove move : moves) {
            int score = minimax(apply(board, move), depth - 1, alpha, beta, true, botColor);
            best = Math.min(best, score);
            beta = Math.min(beta, best);
            if (beta <= alpha) {
                break;
            }
        }
        return best;
    }

    private Board apply(Board board, EngineMove move) {
        MoveResult result = rulesEngine.applyMove(board, move.pathAlgebraic());
        if (!result.success()) {
            throw new IllegalStateException("Illegal move generated by engine: " + move);
        }
        return result.board();
    }

    private int evaluate(Board board, PieceColor botColor) {
        int material = 0;
        for (int r = 0; r < Square.SIZE; r++) {
            for (int f = 0; f < Square.SIZE; f++) {
                Square sq = Square.of(f, r);
                Piece piece = board.get(sq);
                if (piece == null) {
                    continue;
                }
                int value = piece.type() == PieceType.KING ? KING_VALUE : MAN_VALUE;
                // slight advancement bonus for men
                if (piece.type() == PieceType.MAN) {
                    value += piece.color() == PieceColor.WHITE ? r * 2 : (7 - r) * 2;
                }
                material += piece.color() == botColor ? value : -value;
            }
        }
        int myMoves = countMoves(board, botColor);
        int oppMoves = countMoves(board, botColor == PieceColor.WHITE ? PieceColor.BLACK : PieceColor.WHITE);
        return material + MOBILITY_WEIGHT * (myMoves - oppMoves);
    }

    private int countMoves(Board board, PieceColor side) {
        Board probe = board.copy();
        probe.setTurn(side);
        return rulesEngine.legalMoves(probe).size();
    }

    private int terminalScore(GameOutcome outcome, PieceColor botColor) {
        return switch (outcome) {
            case WHITE_WINS -> botColor == PieceColor.WHITE ? WIN_SCORE : -WIN_SCORE;
            case BLACK_WINS -> botColor == PieceColor.BLACK ? WIN_SCORE : -WIN_SCORE;
            case DRAW -> 0;
            case IN_PROGRESS -> 0;
        };
    }

    private int depthFor(BotDifficulty level) {
        return switch (level) {
            case EASY -> 2;
            case MEDIUM -> 4;
            case HARD -> 6;
        };
    }

    private int topNFor(BotDifficulty level) {
        return switch (level) {
            case EASY -> 5;
            case MEDIUM -> 3;
            case HARD -> 1;
        };
    }

    private record ScoredMove(EngineMove move, int score) {
    }
}
