package com.checkers.exception;

/**
 * Machine-readable error codes. Frontend maps them to i18n keys.
 */
public enum ErrorCode {
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    USER_NOT_FOUND,
    USERNAME_TAKEN,
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    GUEST_LOCALE_NOT_PERSISTED,
    GUEST_HISTORY_FORBIDDEN,
    GAME_NOT_FOUND,
    GAME_NOT_JOINABLE,
    GAME_ALREADY_STARTED,
    INVALID_INVITE,
    INVITE_EXPIRED,
    INVITE_ALREADY_USED,
    MATCHMAKING_NOT_IN_QUEUE,
    INVALID_LOCALE,
    INVALID_MOVE,
    BOT_DIFFICULTY_REQUIRED,
    INTERNAL_ERROR
}
